config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Set the root path to the login form
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users do
    resource :game_session, only: [:show] do
      member do
        post :roll
        post :cash_out
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credit.rb
class Credit < ApplicationRecord
  # Relantionships
  belongs_to :user
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  # Relationships
  belongs_to :user

  # Constants
  SYMBOLS = %w[C L O W]
  PRIZES = { 'C' => 10, 'L' => 20, 'O' => 30, 'W' => 40 }
  PER_PULL = -1

  # Instance Methods

  # Roll the slot machine
  def roll
    return unless enough_credits_to_roll

    result = perform_roll
    if winner?(result)
      update_credits_and_rolls(result, PRIZES[result[0]])
    end

    update_credits_and_rolls(nil, PER_PULL)
    result
  end

  # Check if the roll is a winner
  def winner?(result)
    result.uniq.count == 1
  end

  # Determine if a reroll should occur
  def should_reroll?
    reroll_chance = credits < 40 ? 0 : credits < 60 ? 0.3 : 0.6
    rand < reroll_chance
  end

  # Get a sample of symbols
  def get_sample
    SYMBOLS.sample(3)
  end

  private

  # Generate a random result
  def generate_result
    3.times.map { SYMBOLS.sample }
  end

  # Check if there are enough credits to roll
  def enough_credits_to_roll
    return true if credits.positive?

    errors.add(:credits, "must have at least 1 credit to roll")
    false
  end

  # Perform a roll and handle rerolls if necessary
  def perform_roll
    result = generate_result
    return generate_result if winner?(result) && should_reroll?

    result
  end

  # Update credits and rolls based on the roll result
  def update_credits_and_rolls(result, credit_change)
    new_credits = credits + credit_change
    new_rolls = result.nil? ? rolls : rolls << result.join

    update(credits: new_credits, rolls: new_rolls)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relationships
  has_one :game_session, dependent: :destroy
  has_one :credits, class_name: 'Credit', dependent: :destroy, foreign_key: 'user_id'

  # Constants
  INITIAL_CREDITS = 10

  # Callbacks
  after_create :create_initial_data

  # Instance Methods

  # Set up the user's game session
  def set_session
    amount = credits.amount
    amount = INITIAL_CREDITS unless amount.positive?
    create_game_session(credits: amount)
  end

  # Cash out the user's credits and destroy the game session
  def cash_out
    credits.update(amount: game_session.credits)
    game_session.destroy
  end

  private

  # Create initial data for the user (credits)
  def create_initial_data
    create_credits(amount: INITIAL_CREDITS)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    # Set the game session for the current user
    @game_session = current_user.set_session

    # Redirect to the user's game session page
    user_game_session_path(current_user, @game_session)
  end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  before_action :set_game_session, except: [:cash_out]

  # GET /users/:user_id/game_session
  def show
  end

  # POST /users/:user_id/game_session/roll
  def roll
    # Roll the slot machine for the current game session
    @roll_result = @game_session.roll

    # Check if there are any errors related to credits
    if @game_session.errors[:credits].present?
      flash[:alert] = @game_session.errors[:credits].first
    end

    respond_to do |format|
      format.html { render :show }
      format.json { render json: { roll_result: @roll_result, credits: @game_session.credits } }
    end
  end

  # POST /users/:user_id/game_session/cash_out
  def cash_out
    # Cash out the current user and sign them out
    current_user.cash_out
    sign_out(current_user)

    # Redirect to the root path after cashing out
    redirect_to root_path
  end

  private

  def set_game_session
    # Set the game session for the current user
    @game_session = current_user.game_session
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/game_sessions/show.html.erb
<h1>Slot Machine</h1>

<p class="credits">Credits: <span id="credits-value"><%= @game_session.credits %></span></p>
<div class="slots">
  <div id="app"
      data-roll-url="<%= roll_user_game_session_path(@game_session.user, @game_session, format: :json) %>"
      data-user-id="<%= @game_session.user.id %>"
      data-game-session-id="<%= @game_session.id %>"
    >
    <div class="doors">
      <% if @roll_result.present? %>
        <% @roll_result.each do |result| %>
          <div class="door" data-result="<%= result %>">
            <div class="boxes">
              <div class="box"></div>
            </div>
          </div>
        <% end %>
      <% else %>
        <% 3.times do %>
          <div class="door">
            <div class="boxes">
              <div class="box"></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="buttons">
      <%= button_to 'Roll', roll_user_game_session_path(@game_session.user, @game_session, format: :json), method: :post, class: 'game-button roll-button', remote: true, disabled: false %>
      <%= button_to 'Cash Out', cash_out_user_game_session_path(@game_session.user, @game_session), method: :post, class: 'game-button cash-out-button' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseAlwaysWin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'spin' %>
  </head>

  <body>
  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
        var flashMessages = document.querySelectorAll('.alert');

        flashMessages.forEach(function(flashMessage) {
          setTimeout(function() {
            flashMessage.remove();
          }, 2000);
        });
      });
    </script>
  </body>
</html>